remove disabled lines which invalidate formulas on homebrew 3.4.0
Whatever these lines do, the fact remains that current homebrew tells
you that support for them has been removed and that their presence means
the entire repository cannot be used.

e.g.

```
==> Tapping cartr/qt4
Cloning into '/usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4'...
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/treeline.rb
treeline: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/treeline.rb:8

Error: Invalid formula: /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qbzr.rb
qbzr: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the cartr/qt4 tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/cartr/homebrew-qt4/qbzr.rb:8

Error: Cannot tap cartr/qt4: invalid syntax in tap!
```

Remove it and hope that it was not actually needed. Attempting to
install the result seems to work.

Fixes #81